# Generated by Django 4.2.3 on 2023-07-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motiondetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(choices=[(0, "Off"), (1, "On")], default=0),
                ),
                ("token", models.CharField(max_length=100)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.classroom"
                    ),
                ),
            ],
        ),
    ]
